### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by zysNLP** [Awake2714/JianshuSpider#1]
你好，运行了您的代码，出现以下错误，可以帮忙排查下么：
2019-12-26 23:56:43 [scrapy.utils.log] INFO: Scrapy 1.8.0 started (bot: Jianshu)
2019-12-26 23:56:43 [scrapy.utils.log] INFO: Versions: lxml 4.4.2.0, libxml2 2.9.9, cssselect 1.1.0, parsel 1.5.2, w3lib 1.21.0, Twisted 19.10.0, Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) - [GCC 7.3.0], pyOpenSSL 19.1.0 (OpenSSL 1.1.1d  10 Sep 2019), cryptography 2.8, Platform Linux-4.15.0-72-generic-x86_64-with-debian-stretch-sid
2019-12-26 23:56:43 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'Jianshu', 'NEWSPIDER_MODULE': 'Jianshu.spiders', 'SPIDER_MODULES': ['Jianshu.spiders'], 'USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36'}
2019-12-26 23:56:43 [scrapy.extensions.telnet] INFO: Telnet Password: 27bc7709f9737a90
2019-12-26 23:56:43 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats']
2019-12-26 23:56:43 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2019-12-26 23:56:43 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2019-12-26 23:56:43 [scrapy.middleware] INFO: Enabled item pipelines:
['Jianshu.pipelines.JianshuPipeline', 'Jianshu.pipelines.MongoPipeline']
2019-12-26 23:56:43 [scrapy.core.engine] INFO: Spider opened
2019-12-26 23:56:43 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2019-12-26 23:56:43 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2019-12-26 23:56:44 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.jianshu.com/p/7339031f2257> (referer: None)
2019-12-26 23:56:44 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.jianshu.com/p/7339031f2257> (referer: None)
**Traceback (most recent call last):
  File "/home/beyond/anaconda3/envs/bert/lib/python3.6/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/home/beyond/anaconda3/envs/bert/lib/python3.6/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/home/beyond/anaconda3/envs/bert/lib/python3.6/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/home/beyond/anaconda3/envs/bert/lib/python3.6/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/home/beyond/anaconda3/envs/bert/lib/python3.6/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/home/beyond/anaconda3/envs/bert/lib/python3.6/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/home/beyond/anaconda3/envs/bert/lib/python3.6/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/beyond/anaconda3/envs/bert/lib/python3.6/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
    for r in iterable:
  File "/home/beyond/anaconda3/envs/bert/lib/python3.6/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/beyond/Documents/githubs/JianshuSpider-master/Jianshu/spiders/jianshu.py", line 19, in parse
    publish_time = response.xpath('//time[1]/text()').extract_first().replace('.', '/')
AttributeError: 'NoneType' object has no attribute 'replace'**
2019-12-26 23:56:44 [scrapy.core.engine] INFO: Closing spider (finished)
2019-12-26 23:56:44 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 308,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 50342,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 0.996255,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2019, 12, 26, 15, 56, 44, 774204),
 'log_count/DEBUG': 1,
 'log_count/ERROR': 1,
 'log_count/INFO': 10,
 'memusage/max': 55308288,
 'memusage/startup': 55308288,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'spider_exceptions/AttributeError': 1,
 'start_time': datetime.datetime(2019, 12, 26, 15, 56, 43, 777949)}
2019-12-26 23:56:44 [scrapy.core.engine] INFO: Spider closed (finished)

看起来没有抓取到这个页面的信息，怎么回事呢？

**Comment by Awake2714** [comment]
根据错误提示，运行了一下代码，的确报错了，发现是解析规则的错误，网页源码中没有time标签，不过存在时间戳，部分代码已更正如下：
t = int(re.search(r'"first_shared_at":(\d+?),', response.text).group(1)) #时间戳
publish_time = str(datetime.fromtimestamp(t)) #发布时间
words = re.search(r'"wordage":(\d+?),"featured_comments_count"', response.text).group(1) #字数
views = re.search(r'"views_count":(\d+?),"notebook_id"', response.text).group(1) #阅读数
like = re.search(r'aria-label="查看点赞列表">(\d+?)赞', response.text) #点赞数
if like:
likes = like.group(1)
else:
likes = 0
dislikes = re.search(r'"downvotes_count":(\d+),', response.text).group(1) #不喜欢数
author = re.search('"nickname":"(.*?)"', response.text, re.S).group(1) #作者
如有错误，欢迎多多指正​



在 2019-12-27 00:06:04，"Tonny" <notifications@github.com> 写道：

你好，运行了您的代码，出现以下错误，可以帮忙排查下么：
2019-12-26 23:56:43 [scrapy.utils.log] INFO: Scrapy 1.8.0 started (bot: Jianshu)
2019-12-26 23:56:43 [scrapy.utils.log] INFO: Versions: lxml 4.4.2.0, libxml2 2.9.9, cssselect 1.1.0, parsel 1.5.2, w3lib 1.21.0, Twisted 19.10.0, Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) - [GCC 7.3.0], pyOpenSSL 19.1.0 (OpenSSL 1.1.1d 10 Sep 2019), cryptography 2.8, Platform Linux-4.15.0-72-generic-x86_64-with-debian-stretch-sid
2019-12-26 23:56:43 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'Jianshu', 'NEWSPIDER_MODULE': 'Jianshu.spiders', 'SPIDER_MODULES': ['Jianshu.spiders'], 'USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36'}
2019-12-26 23:56:43 [scrapy.extensions.telnet] INFO: Telnet Password: 27bc7709f9737a90
2019-12-26 23:56:43 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
'scrapy.extensions.telnet.TelnetConsole',
'scrapy.extensions.memusage.MemoryUsage',
'scrapy.extensions.logstats.LogStats']
2019-12-26 23:56:43 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
'scrapy.downloadermiddlewares.retry.RetryMiddleware',
'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
'scrapy.downloadermiddlewares.stats.DownloaderStats']
2019-12-26 23:56:43 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
'scrapy.spidermiddlewares.referer.RefererMiddleware',
'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
'scrapy.spidermiddlewares.depth.DepthMiddleware']
2019-12-26 23:56:43 [scrapy.middleware] INFO: Enabled item pipelines:
['Jianshu.pipelines.JianshuPipeline', 'Jianshu.pipelines.MongoPipeline']
2019-12-26 23:56:43 [scrapy.core.engine] INFO: Spider opened
2019-12-26 23:56:43 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2019-12-26 23:56:43 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2019-12-26 23:56:44 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.jianshu.com/p/7339031f2257> (referer: None)
2019-12-26 23:56:44 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.jianshu.com/p/7339031f2257> (referer: None)
Traceback (most recent call last):
File "/home/beyond/anaconda3/envs/bert/lib/python3.6/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
yield next(it)
File "/home/beyond/anaconda3/envs/bert/lib/python3.6/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
for r in iterable:
File "/home/beyond/anaconda3/envs/bert/lib/python3.6/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
for x in result:
File "/home/beyond/anaconda3/envs/bert/lib/python3.6/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
for r in iterable:
File "/home/beyond/anaconda3/envs/bert/lib/python3.6/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in
return (_set_referer(r) for r in result or ())
File "/home/beyond/anaconda3/envs/bert/lib/python3.6/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
for r in iterable:
File "/home/beyond/anaconda3/envs/bert/lib/python3.6/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in
return (r for r in result or () if _filter(r))
File "/home/beyond/anaconda3/envs/bert/lib/python3.6/site-packages/scrapy/core/spidermw.py", line 84, in evaluate_iterable
for r in iterable:
File "/home/beyond/anaconda3/envs/bert/lib/python3.6/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in
return (r for r in result or () if _filter(r))
File "/home/beyond/Documents/githubs/JianshuSpider-master/Jianshu/spiders/jianshu.py", line 19, in parse
publish_time = response.xpath('//time[1]/text()').extract_first().replace('.', '/')
AttributeError: 'NoneType' object has no attribute 'replace'
2019-12-26 23:56:44 [scrapy.core.engine] INFO: Closing spider (finished)
2019-12-26 23:56:44 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 308,
'downloader/request_count': 1,
'downloader/request_method_count/GET': 1,
'downloader/response_bytes': 50342,
'downloader/response_count': 1,
'downloader/response_status_count/200': 1,
'elapsed_time_seconds': 0.996255,
'finish_reason': 'finished',
'finish_time': datetime.datetime(2019, 12, 26, 15, 56, 44, 774204),
'log_count/DEBUG': 1,
'log_count/ERROR': 1,
'log_count/INFO': 10,
'memusage/max': 55308288,
'memusage/startup': 55308288,
'response_received_count': 1,
'scheduler/dequeued': 1,
'scheduler/dequeued/memory': 1,
'scheduler/enqueued': 1,
'scheduler/enqueued/memory': 1,
'spider_exceptions/AttributeError': 1,
'start_time': datetime.datetime(2019, 12, 26, 15, 56, 43, 777949)}
2019-12-26 23:56:44 [scrapy.core.engine] INFO: Spider closed (finished)

看起来没有抓取到这个页面的信息，怎么回事呢？

**Comment by zysNLP** [comment]
收到，爬取的问题解决了，现在有几个小问题还想请教你：
1. 我看你是根据ARTICLE_ID爬的，这样似乎没有针对性，比如我想搜带有关键词“健康”的标题的文章，你有建议修改哪里么？另外你这个ARTICLE_ID我在爬取过程中发现是变动的，是哪个变量控制了它呢？
2. mongodb这里我出了点问题，主要是不熟悉这个db，哈哈，给我报了以下的错误：
['Jianshu.pipelines.JianshuPipeline', 'Jianshu.pipelines.MongoPipeline']
2019-12-27 16:58:39 [scrapy.core.engine] INFO: Spider opened
2019-12-27 16:58:39 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2019-12-27 16:58:39 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6025
2019-12-27 16:58:41 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.jianshu.com/p/7339031f2257> (referer: None)
2019-12-27 16:58:41 [scrapy.core.scraper] ERROR: Error processing {'author': '何鲸洛',
 'dislikes': '13',
 'likes': 0,
 'publish_time': '2017-04-12 16:38:43',
 'title': '60 余家免费正版图片网站，应该是目前最全的的集合了',
 'url': 'https://www.jianshu.com/p/7339031f2257',
 'views': '174009',
 'words': '3229'}
**_Traceback (most recent call last):
  File "/home/lizhi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/lizhi/Documents/githubs/JianshuSpider-master/Jianshu/pipelines.py", line 38, in process_item
    self.db[self.mongo_collection].insert(item)
  File "/home/lizhi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pymongo/collection.py", line 3182, in insert
    check_keys, manipulate, write_concern)
  File "/home/lizhi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/home/lizhi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pymongo/collection.py", line 564, in _insert_one
    doc['_id'] = ObjectId()
  File "/home/lizhi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/scrapy/item.py", line 98, in __setitem__
    (self.__class__.__name__, key))
KeyError: 'JianshuItem does not support field: _id'_**
2019-12-27 16:58:43 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.jianshu.com/p/dcc84b226880> (referer: https://www.jianshu.com/p/7339031f2257)
2019-12-27 16:58:43 [scrapy.dupefilters] DEBUG: Filtered duplicate request: <GET https://www.jianshu.com/p/91ee56ac7bd8> - no more duplicates will be shown (see DUPEFILTER_DEBUG to show all duplicates)
2019-12-27 16:58:43 [scrapy.core.scraper] ERROR: Error processing {'author': 'P友圈PPT',
 'dislikes': '0',
 'likes': '18',
 'publish_time': '2016-02-27 22:40:41',

数据库方面确实不太扎实，我在系统里安装了mongodb，终端mongo命令进去use Jianshu，创建了这个db，但是你setting.py里MONGO_URI = 'localhost'这个我就不太理解了。。。还有MONGO_COLLECTION，还有错误的那个KeyError: 'JianshuItem does not support field: _id'，还望不吝赐教～

**Comment by Awake2714** [comment]
这两天太忙了，一直没来得及回复你，抱歉啊
一、我的这个爬虫是从一篇热门文章入手，爬取推荐阅读的相关信息，当然也可以根据搜索关键词来爬虫，按照个人需求和喜好来吧。
按照你的想法，例如，我们要搜索关于python的文章，点击下一页，可以发现这是一个post请求，返回的是json数据，从中提取slug可以拼接得到文章链接，接下来的解析就很简单了，代码实现就靠你了
二、你谈到的第二个问题是关于mongodb数据库的，在这个爬虫里用到的是pymongo，你可以看看关于pymongo连接数据库的文章；在配置文件settings.py里的MONGO_URI，是自己定义的常量， 是数据连接的host地址；MONGO_COLLECTION同理，是自己创建的集合；关于这个KeyError错误，我在运行的时候并没有报错，你仔细检查下在items.py里的字段有没有写错，或者数据库删了重新建试试呢，另外百度很重要哈哈哈哈，我也只是业余选手，希望能帮到你







在 2019-12-27 17:30:53，"Tonny" <notifications@github.com> 写道：

收到，爬取的问题解决了，现在有几个小问题还想请教你：

我看你是根据ARTICLE_ID爬的，这样似乎没有针对性，比如我想搜带有关键词“健康”的标题的文章，你有建议修改哪里么？另外你这个ARTICLE_ID我在爬取过程中发现是变动的，是哪个变量控制了它呢？
mongodb这里我出了点问题，主要是不熟悉这个db，哈哈，给我报了以下的错误：
['Jianshu.pipelines.JianshuPipeline', 'Jianshu.pipelines.MongoPipeline']
2019-12-27 16:58:39 [scrapy.core.engine] INFO: Spider opened
2019-12-27 16:58:39 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2019-12-27 16:58:39 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6025
2019-12-27 16:58:41 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.jianshu.com/p/7339031f2257> (referer: None)
2019-12-27 16:58:41 [scrapy.core.scraper] ERROR: Error processing {'author': '何鲸洛',
'dislikes': '13',
'likes': 0,
'publish_time': '2017-04-12 16:38:43',
'title': '60 余家免费正版图片网站，应该是目前最全的的集合了',
'url': 'https://www.jianshu.com/p/7339031f2257',
'views': '174009',
'words': '3229'}
**_Traceback (most recent call last):
File "/home/lizhi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
current.result = callback(current.result, *args, kw)
File "/home/lizhi/Documents/githubs/JianshuSpider-master/Jianshu/pipelines.py", line 38, in process_item
self.db[self.mongo_collection].insert(item)
File "/home/lizhi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pymongo/collection.py", line 3182, in insert
check_keys, manipulate, write_concern)
File "/home/lizhi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pymongo/collection.py", line 612, in _insert
bypass_doc_val, session)
File "/home/lizhi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pymongo/collection.py", line 564, in _insert_one
doc['_id'] = ObjectId()
File "/home/lizhi/anaconda3/envs/tensorflow/lib/python3.6/site-packages/scrapy/item.py", line 98, in setitem
(self.class.name, key))
KeyError: 'JianshuItem does not support field: id'
2019-12-27 16:58:43 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.jianshu.com/p/dcc84b226880> (referer: https://www.jianshu.com/p/7339031f2257)
2019-12-27 16:58:43 [scrapy.dupefilters] DEBUG: Filtered duplicate request: <GET https://www.jianshu.com/p/91ee56ac7bd8> - no more duplicates will be shown (see DUPEFILTER_DEBUG to show all duplicates)
2019-12-27 16:58:43 [scrapy.core.scraper] ERROR: Error processing {'author': 'P友圈PPT',
'dislikes': '0',
'likes': '18',
'publish_time': '2016-02-27 22:40:41',

数据库方面确实不太扎实，我在系统里安装了mongodb，终端mongo命令进去use Jianshu，创建了这个db，但是你setting.py里MONGO_URI = 'localhost'这个我就不太理解了。。。还有MONGO_COLLECTION，还有错误的那个KeyError: 'JianshuItem does not support field: _id'，还望不吝赐教～

**Comment by zysNLP** [comment]
哈哈，爬虫的问题已经解决了，数据库方面还需努力，感谢耐心回答，与君共勉，新年快乐！
